# TODO:
# - Rücksetzlogik über Resetpin fehlt noch in Top.sv
# - (* keep *) von allen pins entfernen
# - SRAM final einbauen

meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable magic DRC
    #Magic.DRC: null
    #Checker.MagicDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null
    
    # Save time
    #OpenROAD.IRDropReport: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv

VERILOG_DEFINES: [FUNCTIONAL]

# Enable plugin for better SystemVerilog support
# USE_SLANG: True
# SLANG_ARGUMENTS: ['--keep-hierarchy']

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
PAD_SOUTH: [
    "iovdd_pads\\[0\\].iovdd_pad",
    "iovss_pads\\[0\\].iovss_pad",
    "inputs\\[0\\].input_pad", #buttons[0]
    "inputs\\[1\\].input_pad", #buttons[1]
    "inputs\\[2\\].input_pad", #buttons[2]
    "inputs\\[3\\].input_pad", #buttons[3]
    "inputs\\[4\\].input_pad", #buttons[4]
    "inputs\\[5\\].input_pad", #buttons[5]
    "inputs\\[6\\].input_pad", #buttons[6]
    "outputs\\[0\\].output_pad", #c1clock
    "outputs\\[1\\].output_pad", #c1latch
    "inputs\\[7\\].input_pad",    #c1data
    "outputs\\[2\\].output_pad", #c2clock
    "outputs\\[3\\].output_pad", #c2latch
    "inputs\\[8\\].input_pad",    #c2data
    "outputs\\[4\\].output_pad", #audio_bclk
    "outputs\\[5\\].output_pad", #audio_lrclk
    "outputs\\[6\\].output_pad", #audio_dout
]

PAD_EAST: [
    "outputs\\[7\\].output_pad", #sdram_ba[0]
    "outputs\\[8\\].output_pad", #sdram_ba[1]
    "outputs\\[9\\].output_pad", #sdram_addr[0]
    "outputs\\[10\\].output_pad", #sdram_addr[1]
    "outputs\\[11\\].output_pad", #sdram_addr[2]
    "outputs\\[12\\].output_pad", #sdram_addr[3]
    "outputs\\[13\\].output_pad", #sdram_addr[4]
    "outputs\\[14\\].output_pad", #sdram_addr[5]
    "outputs\\[15\\].output_pad", #sdram_addr[6]
    "outputs\\[16\\].output_pad", #sdram_addr[7]
    "outputs\\[17\\].output_pad", #sdram_addr[8]
    "outputs\\[18\\].output_pad", #sdram_addr[9]
    "outputs\\[19\\].output_pad", #sdram_addr[10]
    "outputs\\[20\\].output_pad", #sdram_addr[11]
    "outputs\\[21\\].output_pad", #sdram_addr[12]
    rst_n_pad,
    clk_pad,
]

PAD_NORTH: [
    "bidirs\\[0\\].bidir_pad", #sdram_data[0]
    "bidirs\\[1\\].bidir_pad", #sdram_data[1]
    "bidirs\\[2\\].bidir_pad", #sdram_data[2]
    "bidirs\\[3\\].bidir_pad", #sdram_data[3]
    "bidirs\\[4\\].bidir_pad", #sdram_data[4]
    "bidirs\\[5\\].bidir_pad", #sdram_data[5]
    "bidirs\\[6\\].bidir_pad", #sdram_data[6]
    "bidirs\\[7\\].bidir_pad", #sdram_data[7]
    "bidirs\\[8\\].bidir_pad", #sdram_data[8]
    "bidirs\\[9\\].bidir_pad", #sdram_data[9]
    "bidirs\\[10\\].bidir_pad", #sdram_data[10]
    "bidirs\\[11\\].bidir_pad", #sdram_data[11]
    "bidirs\\[12\\].bidir_pad", #sdram_data[12]
    "bidirs\\[13\\].bidir_pad", #sdram_data[13]
    "bidirs\\[14\\].bidir_pad", #sdram_data[14]
    "bidirs\\[15\\].bidir_pad", #sdram_data[15]
    "outputs\\[22\\].output_pad", #sdram_dqm[0]
    "outputs\\[23\\].output_pad", #sdram_dqm[1]
]

PAD_WEST: [
    "outputs\\[24\\].output_pad", #sd_clk
    "outputs\\[25\\].output_pad", #sd_cmd
    "bidirs\\[16\\].bidir_pad",   #sd_d0
    "bidirs\\[17\\].bidir_pad",   #sd_d1
    "bidirs\\[18\\].bidir_pad",   #sd_d2
    "bidirs\\[19\\].bidir_pad",   #sd_d3
    "outputs\\[26\\].output_pad", #sdram_clk
    "outputs\\[27\\].output_pad", #sdram_cke
    "outputs\\[28\\].output_pad", #sdram_csn
    "outputs\\[29\\].output_pad", #sdram_wen
    "outputs\\[30\\].output_pad", #sdram_rasn
    "outputs\\[31\\].output_pad", #sdram_casn
    "outputs\\[32\\].output_pad", #gpdi_dp[0]
    "outputs\\[33\\].output_pad", #gpdi_dp[1]
    "outputs\\[34\\].output_pad", #gpdi_dp[2]
    "outputs\\[35\\].output_pad", #gpdi_dp[3]
    "vdd_pads\\[0\\].vdd_pad",
    "vss_pads\\[0\\].vss_pad",
] 

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/p2c

CLOCK_PERIOD: 20

# Floorplanning
FP_SIZING: absolute
# 3880umx5070um including 26um
# for the sealring on all sides
DIE_AREA: [0, 0, 2500, 2500]
CORE_AREA: [365, 365, 2135, 2135]

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 10
GRT_ALLOW_CONGESTION: true

# PDN
PDN_CORE_RING: True

# Override bondpad name
PAD_BONDPAD_NAME: bondpad_70x70_novias

# Bondpad is not yet included in the PDK
EXTRA_GDS:
- dir::../ip/bondpad_70x70/gds/bondpad_70x70.gds
- dir::../ip/bondpad_70x70_novias/gds/bondpad_70x70_novias.gds

EXTRA_LEFS:
- dir::../ip/bondpad_70x70/lef/bondpad_70x70.lef
- dir::../ip/bondpad_70x70_novias/lef/bondpad_70x70_novias.lef

IGNORE_DISCONNECTED_MODULES:
- bondpad_70x70
- bondpad_70x70_novias

# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15
# Ensure minimum spacing for long metals
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5

PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

#MACROS:
#  RM_IHPSG13_2P_1024x16_c2_bm_bist:
#    gds:
#      - pdk_dir::libs.ref/sg13g2_sram/gds/RM_IHPSG13_2P_1024x16_c2_bm_bist.gds
#    lef:
#      - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_2P_1024x16_c2_bm_bist.lef
#    vh:
#      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_1024x16_c2_bm_bist.v
#      - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_2P_core_behavioral_bm_bist_ideal.v
#    lib:
#      "nom_typ_1p20V_25C":
#        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_typ_1p20V_25C.lib
#      "nom_fast_1p32V_m40C":
#        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_fast_1p32V_m55C.lib
#      "nom_slow_1p08V_125C":
#        - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_2P_1024x16_c2_bm_bist_slow_1p08V_125C.lib
#    instances:
#      chip_core.fb.sram0:
#        location: [450, 450]
#        orientation: S
#
## This is an alternative method compared to
## specifying the power connections in the RTL
#PDN_MACRO_CONNECTIONS:
#- "chip_core.fb.sram0 VDD VSS VDDARRAY! VSS!"
#- "chip_core.fb.sram0 VDD VSS VDD! VSS!"
#
## Custom PDN config to connect to SRAMs
#PDN_CFG: dir::pdn_cfg.tcl
#